### ISSUE TITLE
回復了健康

### ISSUE THREAD

**Issue by y49711** [WindOfNet/CgLogListener#2]
超級好用
建議新增功能或者使用者自行新增關鍵字
"回復了健康"
這樣看LINE就可以知道自己處理了沒
不然一直受傷會搞不清楚到底醫好了沒

**Comment by WindOfNet** [comment]
程式是偵測冒險者日誌(對話紀錄檔)，可能只能夠這樣設置(水藍魔力)：

自我治療
```
治療失敗了。
```
p.s. 自己治療成功時不會有訊息，惡化未知
所以要達成你想要的效果，可能得自己打個關鍵字，治療完再發話觸發讓自己知道 XD

接受其他人的治療
```
治療失敗了。
OOO 接受了治療，但是傷勢卻惡化了。
接受了OOO的治療，恢復了少許健康。
接受了OOO的治療，傷勢完全恢復了。
```

**Comment by y49711** [comment]
恩恩 我是玩初心的 
照這樣改
"傷勢完全恢復了。"
或許就可以了吧
沒玩水藍不清楚

**Comment by y49711** [comment]
現在我看我手機只要寫健康就知道沒有新的受傷 不用滑開
